[project]
name = "do"
version = "0.1.0"
description = "Simple focus timer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "playsound3>=3.3.0",
    "rich>=14.2.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
    "ty>=0.0.1a31",
]
